# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3001, host: 3001
  config.vm.network "forwarded_port", guest: 3002, host: 3002
  config.vm.network "forwarded_port", guest: 3003, host: 3003
  config.vm.network "forwarded_port", guest: 3004, host: 3004
  config.vm.network "forwarded_port", guest: 3005, host: 3005
  config.vm.network "forwarded_port", guest: 3006, host: 3006
  config.vm.network "forwarded_port", guest: 3007, host: 3007
  config.vm.network "forwarded_port", guest: 3008, host: 3008
  config.vm.network "forwarded_port", guest: 3009, host: 3009
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/tinydogio/utils/master/vagrantfiles/ubuntu-14.04/node-mongo/provision.sh"
end
